### PR TITLE
Create chain_forks.md

### PR DESCRIPTION
**Pull request by hloo**
[Edited to reflect amendments]

Proposed Ballot Measure:  Serving Zcash users by focusing on the Zcash blockchain and responsible chain forks thereof

Current Text (As Amended):

Any significant effort by the Foundation to develop or promote a cryptocurrency shall be directed at either the (1) Zcash blockchain; or (2) chain forks (chain splits) of the Zcash blockchain that approximately carry forward the percentage stakes of Zcash holders immediately before the fork (split) to the money supply in circulation immediately after the fork (split).

- Yes
- No

Original Text:

Any significant effort by the Foundation to develop or promote a cryptocurrency shall be directed at either the (1) Zcash blockchain; or (2) chain forks (chain splits) of the Zcash blockchain that carry forward the percentage stakes of Zcash holders at the time of the fork (split).

- Agree
- Disagree

### CODE REVIEW

**Comment by hloo** [comment]
## Motivation

### Introduction
As part of a [discussion about foundation governance](https://github.com/ZcashFoundation/ZcashFoundation/issues/56), Zooko raised several questions relating to the ["where the bounds of the Zcash Foundation's authority lie."](https://github.com/ZcashFoundation/ZcashFoundation/issues/56#issuecomment-357319825). This ballot proposal attempts to answers some of those questions by establishing that:

1. The foundation's focus should remain on the current Zcash blockchain and future chain forks (chain splits) of that blockchain.
2. It is appropriate for the Foundation to consider developing or promoting chain forks (chain splits) of the Zcash blockchain.
3. It is inappropriate for the Foundation to commit significant resources to developing or promoting blockchains other than the current Zcash blockchain or chain forks (chain splits) of the current Zcash blockchain.
4. If the Foundation does develop or promote a chain fork (chain split) of the current Zcash blockchain, it should carry forward the percentage stakes of Zcash holders at the time of the fork (split).

### The Zcash Foundation serves users of the Zcash blockchain

Since its inception, the Foundation has stated several times that its serves users of the Zcash blockchain:


> Our mission, most broadly, is to serve the Zcash community and the general public as users of the Zcash protocol and blockchain.
> ([First Announcement from the Zcash Foundation](https://z.cash.foundation//blog/hello-world/), March 7, 2017 (emphasis added))

> [O]ur mission is to be a public charity dedicated to building Internet payment and privacy infrastructure for the public good, ___primarily serving the users of the Zcash protocol and blockchain___.
> ([Zcash Foundation Mission Statement](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/MISSION.md), lasted edited April 9, 2018 (emphasis added))

Scientific research and open source software development funded by the Foundation is likely to benefit other blockchains as well as the Zcash blockchain. For example, to the extent that the Foundation's work improves the Zcash protocol, other blockchains that use the protocol (like ZClassic, ZenCash, and Bitcoin Private) will benefit.  But the central focus should remain on the Zcash blockchain.

Note that this ballot measure is not meant to preclude grant proposals like the currently proposed [$10,000 contribution to Monero's Forum Funding System (FFS)](https://github.com/ZcashFoundation/GrantProposals-2018Q2/issues/17). In the language of the ballot measure, $10,000 would not rise to the level of "significant effort."

### In order to best serve users of the Zcash blockchain, it is essential for the foundation to have the ability to successfully execute a chain fork

As Zooko recently stated:

> In cryptocurrency governance, your negotiating power is equal to the credibility of the threat that you could execute a successful hard fork.
> ([Tweet](https://twitter.com/zooko/status/999735875947790336), May 24, 2018)

The Foundation was designed from the beginning to be independent of the Zcash Company. If the Company goes astray in the future and fails to best serve users of the Zcash blockchain, the Foundation should consider developing and promoting a chain fork.

### With respect to chain forks, current users of the Zcash blockchain are best served by chain forks that preserve each user's percentage stake 

Many users have expended significant resources to obtain a ZEC stake, either through mining ZEC, purchasing ZEC from an exchange, or earning ZEC by selling goods or services. A Foundation-backed chain fork should respect current ZEC holders by preserving each user's percentage stake at the time of the fork.

**Comment by amiller** [comment]
Thanks for this suggestion! I am excited to have a "tricky issues" ballot measure like this on our first voting experiment.

I wonder what guidance this ballot measure would have around the grey boundaries... For example, what about a hypothetical fork ZEC2 that mints an additional 10,000 ZEC2 for the fork's development  team or something like that (such that there would be 21,010,000 ZEC2 in total). That would preserve  everyone's percentage stake up to a .001 fraction, and therefore is pretty close to the spirit of this. I would say that as written this ballot establishes the principle and leaves it up to further decision making to deal with the boundaries. What do you think?

**Comment by hloo** [comment]
@amiller Thank you very much for your feedback; it caused me to rethink the language of the ballot measure. I would like to change the language from:

" . . . carry forward the percentage stakes of Zcash holders at the time of the fork (split)"

to

" . . . **approximately** carry forward the percentage stakes of Zcash holders **immediately before** the fork (split) **to the money supply in circulation immediately after the fork (split)**."

What I'm aiming to preclude are airdrops that significantly and immediately dilute pre-fork percentage stakes, like what Bitcoin Private did with their airdrop to Bitcoin holders. The Bitcoin Private airdrop significantly and immediately diluted the percentage stakes of ZClassic holders.

On the other hand, I don't want this ballot measure to preclude raising the 21 million coin cap. (I personally hold the cap sacred, but I don't believe the foundation should anoint the cap as sacred, nor do I want this ballot to address whether it is permissible to raise the cap.)

So, back to your example of slightly raising the cap to fund the fork's development team. The ballot measure (as amended) would not preclude such a fork since a .001 fraction falls within the ambit of "approximately." Furthermore, even if this hypothetical fork development team also decided to significantly increase the total money supply by doubling the mining reward, that would be fine too, since the increased money supply would be put into circulation slowly over time.

The grey boundaries, as you suggested, would be left to further decision making.

**Comment by hloo** [comment]
Under the framework of this ballot measure, the questions that @zookozcash raised back in January regarding ["where the bounds of the Zcash Foundation's authority lie"](https://github.com/ZcashFoundation/ZcashFoundation/issues/56#issuecomment-357319825) would be answered as described below.

Note that the preamble to all the questions is:

> Could it ever be appropriate, and possible, and Good and Right, for the Zcash Foundation to:

Questions:

> Support a backwards-incompatible (so-called “hard forking”) network upgrade, such as Overwinter and Sapling that the Zcash Company is developing and deploying?

**Yes.**

> Oppose such a backwards-incompatible network upgrade that the Zcash Company is developing and deploying?

**Yes. Since the Foundation is independent from the Company, the Foundation is free to oppose hard forks proposed by the Company.**

> Develop and deploy its own backwards-incompatible network upgrade? What about one that might be opposed by The Zcash Company or by another powerful stakeholder? (See also A Future Friendly Fork.)

**Yes. Since the Foundation is independent from the Company, it is appropriate for the Foundation to unilaterally develop and deploy its own chain forks of Zcash. The Foundation's ability to do so increases its leverage in negotiations with the Company and other entities.**

> Support an upgrade that changes the 21M total supply cap?

**Yes. Without addressing the wisdom of such an upgrade, this ballot measure would not preclude the foundation from supporting it.**

> Support an upgrade that changes the Proof-of-Work algorithm?

**Yes. Without addressing the wisdom of such an upgrade, this ballot measure would not preclude the foundation from supporting it.**

>Support an upgrade that switches from Proof-of-Work to Proof-of-Stake?

**Yes. Without addressing the wisdom of such an upgrade, this ballot measure would not preclude the foundation from supporting it.**

>Support an upgrade that changes the amount or recipients of the Founder's Reward?

**Yes (without addressing the wisdom of such an upgrade), but only prospectively.**

> Support an upgrade that changes the amount or recipients of the block reward? (For example, "50% of the block reward goes to the miner who found the block, and 50% of the block reward goes to some specific public keys selected by some specific process.")

**Yes (without addressing the wisdom of such an upgrade), but only prospectively.**

> Contribute improvements (for example, security audits, security fixes, performance and feature upgrades) to other coins such as Monero?

**Yes, unless the contribution requires the Foundation to expend "significant" effort or resources.**

> Develop their own complete Zcash implementation?

**Yes, so long as the implementation is directed at the current Zcash blockchain or chain forks thereof.**

> Develop their own complete Monero implementation?

**No. This would constitute a "significant effort by the Foundation to develop or promote a cryptocurrency." The ballot measure requires that significant efforts to develop or promote a cryptocurrency must be directed at the Zcash blockchain or chain forks thereof.**

> Launch a new coin?

**No, unless the new coin is a chain fork of the Zcash blockchain.**

> Launch a "fork"/"airdrop", such as by forking the Zcash blockchain or the Bitcoin blockchain or the Ethereum blockchain, and/or by giving all current holders of other coins free newly-generated coins?

**No. The ballot measure precludes the Foundation from launching forks of blockchains other than the Zcash blockchain. With respect to forking the Zcash blockchain and then airdropping coins onto holders other coins, this is also precluded by the ballot measure, because it would immediately dilute the percentage stakes of Zcash holders by significantly increasing the money supply in circulation immediately after the fork.**

**Comment by HershyatHatch** [comment]
@hloo - so, my question is to the wording of the proposal:

I understand that if we vote 'agree' are we voting that the foundation can only assign significant effort to zcash or forks?

But.... if we vote 'disagree' are we voting that the foundation could infact assign significant effort to an even bigger wider array of projects/blockchains?

**Comment by hloo** [comment]
@HershyatHatch that is a great question. There is more than one reason that someone could vote "no." Some possible reasons:

1. As you mentioned in your question, the voter might want the foundation to be able to assign significant effort to cryptocurrencies that are not Zcash or a chain fork of Zcash.

2. They may only want the Foundation to work on Zcash, not any chain forks of Zcash.

If the ballot measure fails, there is no way of immediately knowing which reason was more prevalent amongst voters.

**Comment by HershyatHatch** [comment]
@hloo Thanks for your response.

So, I think we may need to get more clarity and specificity into the ballot measure. For, I agree with your point:

_"If the ballot measure fails, there is no way of immediately knowing which reason was more prevalent amongst voters."_

If we naturally follow that logic on, the inverse must also be true - if the measure succeeds we must also be uncertain as to what exactly the voters were voting for.

I do not raise these concerns as a debate-for-the-sake-of-debate exercise. I see your original points and questions relating to this measure as extremely important and impactful to the future The Foundation's charter. I'll give you an example of what what we may be unknowingly voting on:

Let's say there is a person or persons working on new innovations in the space of 'Transaction Privacy on The Blockchain' Perhaps their work builds on zk-snarks or perhaps their work is an even superior innovation that is not specifically 'just' an upgrade of the protocol and what they are building is, essentially, another project. 

However, their work is, to The Foundation's mind, fair, legal and tremendously beneficial. But suddenly, some state-like actor - for reasons of censorship or suppression - decides to arbitrarily take actions to shut down their work and progress. Then let us suppose that The Foundation is in the position to provide that individual (or individuals) with support - whether that be financial or by bringing public attention to their fight or etc.

What should The Foundation do?

Are we able to refer back to this ballot measure for clarification? Or, because of the ambiguity of what the result of this measure means, will we have folks arguing for action or no-action both saying that this vote supports their side of the argument?

This is where my concerns come from. I think we may need to get everyone on The Community Panel a little clearer about what exactly we are voting on here. We can either take steps to narrow down this ballot measure (e.g wording that says "this measure only relates to actions The Foundation can or cannot take around forks and/or it's abilities and powers to drive and create such forks."). Or we can broaden out it's scope to drive discussion and resolution about wider capabilities of The Foundation's charter.

The Foundation's independence from the Company is important to everyone. We, as a Community Panel, need to be clear in the setting the guidelines for that independence.

@acityinohio @hloo  thoughts?

**Comment by hloo** [comment]
@HershyatHatch your comments touch on fundamental issues of statutory interpretation. When interpreting the meaning of a statute, the [legislative intent](https://en.wikipedia.org/wiki/Legislative_intent) is relevant but also difficult to ascertain, because each legislator has their own individual intent. It is an inexact exercise for sure.

In general, all ballot measures, including all the ballot measures in this Foundation straw poll, suffer from this problem. Take the ASIC resistance ballot measure for example. Some voters might vote against it because it goes to far, while others might vote against it because it didn't go far enough.

One of the reasons that I favored wording the ballot choices as "yes" and "no" instead of "agree" and "disagree" is that a vote is more accurately a "yes" or "no" question. There are many reasons to vote "yes" on a measure even though you may not entirely agree with it.

Back to your hypothetical. This ballot measure only restricts the Foundation from developing and promoting cryptocurrencies that are not Zcash / Zcash chain forks. It says nothing about general research. Your hypothetical "Transaction Privacy on The Blockchain" would be fine, and might help Zcash in the future.

If the activity in question is not in the category of developing or promoting a cryptocurrency, the ballot measure places no restrictions on the Foundation performing that activity.

**Comment by Souptacular** [comment]
Thanks for writing https://github.com/ZcashFoundation/Elections/pull/14#issuecomment-396414352. It cleared up some questions I had about support towards other coins. Specifically the ZCash company has previously [worked with Ethereum on implementing zkSNARK enabling math into the Ethereum protocol](https://blog.z.cash/ethereum-snarks/) and I was afraid this measure would prevent something like that happening in the future. I now know that is not true unless a "significant" effort would need to be applied.

**Comment by zookozcash** [comment]
Also please note that the Foundation has no authority over the Company, so
even if this ballot initiative were to pass and the Foundation Board were
to start enforcing it on Foundation business, this wouldn't prevent the
Company from contributing significant effort to other projects.

(Of course, the Company would do something like that only if — in the
opinion of the CEO (me), the Company Board of Directors, and the Company
Strategy Team — it were in the best interests of the Company's
stakeholders.)

**Comment by Souptacular** [comment]
Thanks for reminding us of the distinction @zookozcash! :)

**Pull request merged**
