### PR TITLE
Create asicresistance_ballot.md

### PR DESCRIPTION
**Pull request by amiller**
This is a very quick and rough ballot proposal based on the "Let's talk about ASIC Mining" forum thread. It reflects just my own personal effort, and has not been validated by other members of the Zcash Foundation, the community, or the Zcash Company. It's put up here for review and to jumpstart the conversation about what role the Foundation could play and how our ballot process can help the discussion. I invite folks from the community to continue discussing this here and in the forum!

*Edit: putting full ballot proposal here for readability from the election links.*

# Ballot Proposal: ASIC Resistance as a value and priority for the Foundation

Proposed ballot entry:

```
The Zcash community wishes to preserve ASIC resistance, discouraging the use of ASIC mining equipment in favor of GPU mining equipment. The Zcash Foundation should therefore adopt this as a priority.

- Agree
- Disagree
```

## Background

ASIC mining has recently emerged as an widely-discussed issue in several cryptocurrencies, including Zcash but also Monero and Ethereum. Bitcoin mining has been well-known to be dominated by dedicated ASICs, since SHA256 is ASIC-friendly. Zcash's proof-of-work mining puzzle is based on a technology, Equihash, which is intended to be ASIC-resistant but GPU-friendly. Although Monero and Ethereum also feature (different) ASIC-resistant proof-of-work puzzles, there appear to be effective ASICs in use or on the Horizon. To avoid ASICs, [Monero has recently hardforked](https://cointelegraph.com/news/monero-hard-fork-appears-successful-as-devs-shun-bitmains-asic-miners) to a new proof-of-work puzzle, while Ethereum is developing a proof-of-stake alternative. A discussion on ASIC resistance can be found here: [forum.z.cash](https://forum.z.cash/t/let-s-talk-about-asic-mining/27353).

Zooko (the chief of Zcash Company) has challenged the framing of this question, arguing that we do not know if ASIC resistance  actually achieves decentralization. [(1)](http://www.crypto-news.in/news/alt-coins/zcash-founder-zooko-not-interested-asic-resistance/) [(2)](https://forum.z.cash/t/let-s-talk-about-asic-mining/27353/151) As such, this is an important topic to include in the ballot to the Community Approval Panel, since it may be a point of disagreement between the Zcash Company and the broader community.

## Scope of this proposal

This scope of this proposal is left deliberately vague, and does not prescribe a particular action for the Foundation to take. Nor does the outcome indicate a particular technical approach in response. If this proposal is accepted, the Foundation will adopt this as a priority and come up with an action plan to outline in a blogpost. 

Possibile responses include:
- allocating resources to investigate technical options (how feasible are ASICs for equihash? Would a parameter change be sufficient? What other proof of work puzzles would fare better?)
- lobbying the Zcash Company to prioritize ASIC resistance in their roadmap
- hiring engineering staff to contribute an implementation of the above

### CODE REVIEW

**Comment by autotunafish** [comment]
Without evidence that a measure taken of asic resistance would be more beneficial to the Zcash mission than harmful, the board should take extreme care in considering this issue being put ballot

**Comment by garethtdavies** [comment]
I favour something a bit more actionable for the ballot entry. How about something along the lines of:

> The Foundation should produce a proposal for future management of the POW algorithm to best achieve the aims of mining decentralisation

This makes no assumptions (other than it remains POW) and doesn't frame the argument and can contain any evidence (or lack thereof) to substantiate any proposal from the Foundation. Also, if a change of POW is deemed necessary to achieve those stated aims a concrete plan should be proposed to implement it which identifies potential costs, risks, (realistic) timescales etc... for such a change to be implemented. Then I'd assume such a proposal could be put up for a vote to (hopefully) achieve broad community consensus and provide clear direction.

Practically, perhaps this could be spearheaded by a working group (preferably including a member of Zcash Co) or utilising an existing one if relevant, with additional resources provided as necessary.

**Comment by flame05** [comment]
@autotunafish Mr. **EXTREME** care,
 how are you suppose to get evidence without changing anything?

I wouldn't consider splitting work as myriad coin. 
I would consider updating equihash parameters so we could acknowledge **IF** and **HOW MUCH** ASIC is present.

**Comment by mineZcash** [comment]
Bitmain has begun taking pre-orders for Equihash ASICs. https://shop.bitmain.com/product/detail?pid=00020180503154806494uGcSyiu806FD

Which is a good indication that Zcash ASICs may have been already running for months behind the scenes since Bitmain has a record of taking profit first, then selling to the general public. As seen by the Monero hard fork hashrate drop after the ASICs moved to another coin. 

So getting some sort of official response/ plan of action in place needs to happen ASAP. 

I'm not sure of how this ballot will fit in with the the developers plans, but it seems like a good place to start.

**Comment by zookozcash** [comment]
> Which is a very good indication that Zcash ASICs have likely been already running for months behind the scenes since Bitmain has a record of taking profit first, then selling to the general public. As seen by the Monero hard fork hashrate drop after the ASICs moved to another coin.

Hey, why do you think that Bitmain does this? I've heard a lot of people claim it, including I've talked to quite a few "behind the scenes, I shouldn't be telling you this" people. _Most_ of those behind-the-scenes people claim that they know that Bitmain does this, but they can't give me any evidence of it. _A few_ of them give equally convincing testimony that they know that Bitmain has not done this (yet) for Zcash, but they also can't give me any proof one way or the other.

The only hard evidence I've seen yet is the disappearance of 50% of the hash rate from XMR after the PoW-change fork. That's evidence! But it is also somewhat circumstantial. Did that 50% go to one of the old-PoW forks? Are there more than one old-PoW fork or just one? Is there any other way to determine what portion of any of the (old-PoW-)XMR, ZEC, or ETH hashrate is ASIC ?

But anyway, what is your reason for believing that Bitmain practices this secret-pre-release-mining practice?

**Comment by tony971** [comment]
Just as a counterpoint to the "asics breed loyalty" argument, I built my mining rig specifically to mine zcash and zcash alone. If asics start dominating the hashing power, I'll be forced to switch coins in order to remain solvent. This won't be an issue for future miners, who can start off with asics. But it screws the early adopters with high startup costs.

**Comment by mineZcash** [comment]
@zookozcash I don't think anyone has emprical evidence of this.  The only things we can point to are 

1. Monero's and others coins hard forks resulting in huge hashrate drops.

2. Many users have complained that thier "new" equipment is dusty and shows signs of use:

 https://bitcointalk.org/index.php?topic=2244677.0

https://www.reddit.com/r/Bitcoin/comments/7txh2f/sooo_you_guys_are_aware_that_bitmain_is_selling/

https://bitcointalk.org/index.php?topic=646982.0


3. It makes fantastic business sense: Make a miner that is super efficient (big capital outlay), slowly add your units to the pools to appear as organic hashrate growth, let them run for several months to pay off your intial investment + profit , then begin rotating old stock with new by selling old stock to the public.

I get your point, there isn't a good way to "prove" any of this speculation.  

The only way to confirm it would be to shift Zcash Equihash parameters that thier hardware is built for and watch the hashrate charts.

**Comment by zookozcash** [comment]
Thanks, mineZcash!

**Comment by zookozcash** [comment]
I'm still skeptical of "Are you in favor of this good thing?" ballots. I guess if we had 100 such different good things we'd find out that they are all winners. I much prefer "What's more important to you: this good thing or that good thing?". What I think is important to balance right now is "Wider distribution of the mining rewards or incentive-alignment between miners and hodlers". FWIW, I currently prefer wider distribution of the mining rewards, but I think looking back on _that_ question in a year or two will be more informative than looking back on "Are you in favor of Wider distribution of the mining rewards?".

**Comment by bjames301** [comment]
I just wanted to chime in on this issue. First off I want to thank all the developers that have made Zcash what it is today. I have been in Crypto since 2011 and I have witnessed first hand BITMAIN's horrible tactics. They destroyed CoinTerra the only US ASIC company that existed and then they nearly crippled BITCOIN with Bitcoin Cash. Fundamentally I am not against ASICS however, as long as BITMAIN controls the landscape with their clearly evil practices I am very anti ASICS . Ive supported ZCash since day one and I have spent a lot of my personal time educating people on how to use it and on its massive potential. Its my personal thoughts that until the landscape of ASIC manufactures changes Zcash needs to fork. If the fork or some incentive for GPU miners is not made, I will shed real man tears and be forced to move to another privacy coin. I believe in crypto and freedom first. BITMAIN represents greed oppression and deception. I ask in the most humble way possible for you all to not discount those who have supported you all the most.  


Sincerely,
A humble GPU Miner

**Comment by polminer** [comment]
Must support to GPU early miners and small GPU-rigs.
We GPU Miners want FORK!

If you want PUMP (from increase diff) + 20%  JUST SAY IT, Zooko! We want answers.
Do fork and do your job and you will get your MOney in LONG, Zooko,without collusion with ASIC producers, who want sell their useless metal EVERY 6 month- 1 year.

**Comment by tony971** [comment]
I think the main issue I have with asics is that once a private party has control of their distribution, there are inherent road blocks to gaining a significant share. Hell, I wouldn't even mind a zcash foundation-sponsored asic as long as it meant maintaining equal scarcity across the board.

**Comment by polminer** [comment]
Zooko want that 80% Asic controlled ASIA miners who has fastest shipping in region.
If you will support ASICs  you will get centralized useless network 
and all GPU miners leave your to other asic resistens Forks.

**Comment by polminer** [comment]
It seems that Zooko is working for the monopolist Bitmain.

Zuko  retire or fork!

**Comment by mineZcash** [comment]
@polminer this isn't Reddit, this is GitHub so spamming comments and throwing out random accusations that don't further the ASIC conversation are not welcome in this thread.

I would suggest that @amiller remove and block users if necessary.

**Comment by polminer** [comment]
[REDACTED]

@acityinohio modified this comment because it was not germane to the discussion and against the [Values](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/VALUES.md) of the Zcash Foundation. @polminer if you engage in abusive and non-productive discussion again you will be blocked from commenting on any @ZcashFoundation repos.

**Comment by solarismedic** [comment]
I haven't decided whether I'll buy a Z3 or not, but I do own ASICs, I do not own any GPUs that are used for mining only (though I'm huge into gaming in my earlier days).  Now with that said, I will say this:  We are at a very beginning of what is going to be a very long (and fruitful) road in the crypto world.  While I completely understand that people that have invested in GPUs for mining, we all need to step back and understand 1 thing.  GPUs mining is NOT how this is all going to play out as this space matures.  Simply put, GPU mining does not scale and is not optimal in any way shape or form.  When we look at electricity use, material use, hw/sw interfacing and get right down the the technical details of how a mining rig operates - it is not a long term solution.  Now, does that mean there is 100% no place for GPUs in mining?  Well....ofcourse not.  GPUs are a great way for people to get into mining, and for a coin to mature.  Some may see moving from GPUs or FPGAs to ASICs as 'biting that hand that feeds you', but I see this as a simple evolution.  As any investor in any equipment that one utilizes to create revenue and profit, one absolutely must do their own market analysis and risk assessment.  Before diving into any sort of investment into GPU mining, one simply should ask themselves, is THIS futureproof?  If so or if not, how long?  Can I see the market changing, regardless of if we control it or not?  Saying biting the hand is like saying, we should never get married and always live in your mother's house and only listen to your mother and not your wife.  You grow, you evolve, you move on.  Does it mean you leave the ones that built you up on the side of the road while you drive off with your new shiny ASIC partners?  No.  Ideally not.  But I think EVERYBODY in this crypto space needs to wake up and consider the fact that ASICs moving into a space is an indication that MORE MONEY is being poured into your coin.  It is actually making the entire ecosystem more robust.  Ofcourse allowing 1 single company (bitmain) to pump out gear is not a very good idea.  But everything's got to start somewhere.  You can see with the SHA265 space, that there is already a considerable amount of gear coming into the market.  Let's not forget, these companies were probably only compelled to spin up their operations within the last 12 months and products are not finally starting to come online.  So while there is a big player with the capital to launch first, there always must be that 1 catalyst that brings players into the space.  They are big, they take the risk.  If it's good, they drink the first sip which is always the sweetest.  If the market disagrees and they fail, they eat the loss.  But I'll reiterate, money entering the industry can ONLY be a good thing at this stage.  That gets the attention of investors, the whales, the institutional players, and that's when you'll reap your real rewards.  Not from mining with teaspoons your entire life.

I'll put it a different way for those that can't see it.  If Bitmain and Halong Mining (just as an example) decided tomorrow that they would sell the chips and allow assemblers to make their own boxes, would this change your opinion?  Now change Bitmain's name to Nvidia and HM to ATI, you essentially have the GPU mining business model.  2 big players, "controlling?" the market.  It can appear more centralized to some, and more decentralized to others.  But one thing is for certain, one is the future, and one is the past.  Can you see which is which?

**Comment by lordfeo** [comment]
> Did that 50% go to one of the old-PoW forks? Are there more than one old-PoW fork or just one?

most of these 50% gone to "monero classic" http://monero-classic.org/  supported by antpool and bitmain, you can see in the footer.
Here you can see "monero classic" has more hash rate than original chain (original chain mains supported by monero original team) http://explorer.monero-classic.org/
Orginal chain hash rate: 497 Mh/s
monero classic hash rate: 613 Mh/s

What if an algorithm's parameters change time to time automatically like difficulty? for example every X block dependent to factor Y.

**Comment by asbjornenge** [comment]
My two zec;

* It will happen eventually
* It will hurt, sooner > later
* It is MUCH simpler to mine using an ASIC miner than a GPU rig
* Have a look at the pools and top miners, it's already farms providing 90% of the hashpower

Ending with a small anecdote; 
My dad wanted to set up a miner in the basement. I helped him put together a GPU rig, but it was a constant hassle for him. GPUs kept failing, needed overclocking, powerlimit tweaking etc. OS needed updates and he had to learn about the command line. Eventually he sold it and got an ASIC instead. It (and a few friends) have been running constantly for over a year and all he has to do is to check his pool stats once in a while.

So... I'm not sure how this whole "GPUs will yield a wider distribution of coins" actually holds true.

Bring on the ASICs ✨🚀

**Comment by tony971** [comment]
> Now change Bitmain's name to Nvidia and HM to ATI, you essentially have the GPU mining business model. 2 big players, "controlling?" the market.

If Nvidia and AMD were in the crypto game themselves, we'd see a lot less GPUs hit the market. But since they're not, it's not really the best comparison. Let's not pretend that Bitmain is some benevolent research firm, trying to advance the tech for mass adoption. A hell of a lot of these are gonna remain in their hands, actively competing with the ones they sell. All the while, they get to control the quantities that each side has.

**Comment by autotunafish** [comment]
Recent difficulty rate is at an organic enough grow that I was actually able to predict the last Spike towards the end of February https://forum.z.cash/t/diffuculty-increase/26844 were about due in coming weeks for another, its just a fractal

**Comment by solarismedic** [comment]
btw, for those that say the reason to buy GPUs to mine is because there is resale value when you're 'done' with the equipment, this is exactly when you would sell if you plan to stay with these algos that are open to ASICs entering.  Let's not forget that there are pros and cons for your choice of mining gear. 
 Resale value is a pro, just don't forget what the cons are.

**Comment by solarismedic** [comment]
@tony971 Correct, it's not the absolute best comparison, but it's not far from the truth.  Them not being heavy into the crypto game is a business decision and business decisions change with the winds of business.  What you think you see today will more than likely not hold true later.  Infact the more certain you think you are, the less certain the outcome since the overconfident space is the most ripe for disruption.  Watch what happens when GPU sales drop as they inevitably will when bitmain cozys up to more ASIC-friendly coins.  That and add a dash of large banking interests into the space (don't forget those same banks help green and red deal with the markets and issue bonds and other financing tools that they partner up together for), don't think for a moment that the only semiconductor company interested in the crypto game is bitmain.  There are large players watching, waiting, and quietly doing their research.  Like Intel (but so far their progress is laughable).  Anything that drives sustainable growth to the chip industry will have the attention of big money.  I don't particularly like bitmain personally, but put any large corporation that spends tens/hundreds of millions of dollars in R&D each year or 2, you better believe they are going to be in it to make money.  Bitmain knows that these are their golden years and their chance to seize incumbancy as king in crypto ASICs and beyond.  As the space matures, other players will come in to take their stake.  This is nothing new - every industry is like this.  Innovator -> Market leader -> competition -> technology war -> price war -> saturation -> commoditization -> consolidation -> disruption -> rinse and repeat.

This has been the path walked by pretty much every industry and industry leader at some point in their life.  Bitmain knows this, so watch for them to be onto the next thing before the competition gets a little too close.  If you want some dry reading, look up what they're doing in the AI space.

**Comment by MateosDev** [comment]
If ASICs are the future, we need to see more decentralization in the form of more Bitmain competition. They're never going to come out and admit that they've been hashing with six month to one year old hardware before they sell it. That "proof" would destroy their strategy IMO. 

I too am a humble miner. I am for the ASIc resistant fork as long as Bitmain continues their antics. I hold some ZEC but don't currently mine it, but I can say that I was always under the impression that the coin was ASIC- Resistant.

I guess we won't know how much of the hashrate is really from ASICs until the fork occurs. I'd rather err on the side of caution, because again there is not a distributed market of ASIC mfgs. Bitmain has too much control.

**Comment by solarismedic** [comment]
@ShatterDay It will come. You should have more faith in capitalism and free markets.

btw, there's nothing wrong with hashing first.  that's well within their right.  selling used gear?  that's a gray area, maybe they are not actually taking equipment off the shelf and selling it to you. but it's an unknown granted.

a fork will only hurt the coin.  don't forget, you're competing with other coins.  you're not competing with bitmain.

**Comment by autotunafish** [comment]
Just did a little quick Research into the history of Chinese business ethics and it's actually a fairly interesting and conflicted story, overall it's a confucian driven system which tends to favor responsibility to family and does to this day, there is cited in an article a confucian admonition, that a person who sees his father steal a sheep should not turn his father over to the authorities. Counter arguments are presented, Mozi, a 5th century Chinese philosopher, argued favoring the family as the root of corruption and instead advocated laws that protect everyone equally. I like Mozi https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.scu.edu/ethics/focus-areas/business-ethics/resources/business-ethics-in-china/&ved=2ahUKEwjPr_72luvaAhVJ3IMKHZnBCIQQFjAAegQIBxAB&usg=AOvVaw2TCNZA9VSarJE1-6_t4wdX Edit- to get a better idea of bitmains motivation, i think it was beneficial for perspective of the whole situation, i looked at a few other articles too but not super deep

**Comment by vannig** [comment]
I would take the courage to underline some facts -
1.  Chinese business ethics is far from honest foundations. They don't want you to lose interest but in the meantime, they want to gain for themselves as much as possible.
2.  mineZcash commented -  Zcash ASICs may have been already running for months behind the scenes.
And it's completely right claim because the whole indicators shout about this fact. Only blind will not see these. And those facts for Monero is so evident. You can doubt cancer till you make analysis, but there is always the signs of presence at the early stage.
3. There is no problem for GPU miners to switch to another algo/coin- and we don't know in longterm how would it affect Zcash and it's infrastructure. But dependence on Bitmain is not good at all.
4. It was promised to stay at the ASIC resistant way so it must be done. Look at Monero developers - they believe in their creation and had no hesitations on whether to protect their coin or not. And it's the right strategy because Asics are fleeting and GPU mining is more flexible and far-sighted option.

**Comment by raodluffy** [comment]
In the beggining coins are anti Asic, but then they forgot about this and don't care 
Cryptos gained my attention because decentralization
Every person can have  a PC and mine with CPU + GPU and gives more security to network, also helps to spread the coin and the community will grow
This is FACT
With Asics, only a few big farms will control the mining, Bitmain are the most powerful company, it's just like banks that we are fight against with cryptos
BigFarms can buy as many pieces of Asics they want 
With GPUs, every person can buy the exact same hardware as big farms

**Comment by solarismedic** [comment]
@vannig 
1.  I wonder why you're in the mining game at all then, or for that matter, crypto at all.  the semiconductor game is essentially a chinese one now.  before that, all/most of that was in the western world (and japan).  no big deal here, it's market evolution just like any other sector of business.
2.  it's well within their right.  they spent the r&d money to develop the product.  there is nothing that says they have to sell it rather than use it for themselves.  you'd do the same if you were smart.  don't talk like you paid them to develop the product and they didn't hand it over to you when they should have.  you are entitled to nothing until you've paid for the product.  i have no doubt they have developed products that have never hit the sales market at all because of taping out problems what not.  nobody pays for that but them.  i'm not saying it's ideal for the market, but it's the free market in action.
3. you can switch. just know you're gpu mining rig is NOT a scalable solution.  it's a great startup one, but if you're building a GPU mining farm at large scales, I would have to say you have tunnel vision.  there are more efficient and cost effective ways to do something at scale.  again, free market in action.
4.  was it promised?  I'm not aware of this, but would be interested and open to hearing what the exact commitment was.  I get that if there was a hard commitment, that reneg-ing on that would be a dick move.  we are in agreement here.

@raodluffy ASICs don't mean centralization.  true, 1 company is king right now, but you can see they are quickly diversifying their product portolio because there are too many competitors coming online and offering SHA256 ASIC products now.  this is the free market in action.  the response time is not instant as new products need development time as does your coin, but have faith in capitalism.

**Comment by bjames301** [comment]
@solarismedic  1.  Its well within my right to not support an evil and manipulative company period. So any justification of R&D money spent means nothing to me.  Its like saying "Oh this country spent R&D on building chemical weapons so they are with in their rights to use them". You are naive and missing the entire point of this all. Its not ASICS we have an issue with, its BITMAIN! No song and dance you can articulate in writing will change our views on this matter.

**Comment by solarismedic** [comment]
@bjames301 nobody is challenging your right to support whatever you want.  and i wholeheartedly agree with you, spend your money how you want.

where i differ in opinion is that ASICs will be the death of crypto.  I do not think they can be compared to chemical weapons, a bit of a silly analogy to be honest.  And, the issue is that they hash first sell later.  In your analogy, the ones (and it's ALOT of people) that buy their 2ndhand gear later are equally as guilty if not more so.  If you are simply to take what's happening in the market, 3 of the 4 strongest and most potential coins on the market (as well as supported by exchanges)  have ASICs securing them.  The 4th is about to have ASICs enter the hashrate.  So while you're certainly entitled to your opinion, reality does not back up your theory.

Yes today Bitmain is the forerunner.  They are not the only one in the game.  There are competitors now, and there are ALOT more competitors coming online.  Your argument is shorterm and will be completely moot in 1-2 years.  The only question is, where are you going to fit into the game in that time.

I'm not trying to change your views, I think that's not a very effective method of communication.  I'm simply offering you a more complete picture.  You don't need to preach to me about what's bad about 1 controlling entity - that's all sorts of wrong on every level.  But this space is not static, it has changed and will continue to change.  But nevermind that if you want....whether i'm wrong or right is immaterial.  The only thing that should matter to you is if you'll be on the winning side or losing side in 12 months.  Trying to sway people's opinion is just a stupid thing to do.  DYOR, and decide for yourselves.  I'm impartial either way, I'm going to go with what makes sense to me, bitmain or otherwise.

**Comment by tony971** [comment]
I'm not sure an oligopoly is much better than a monopoly when it comes to controlling a currency. Zcash doesn't have many direct applications right now. And it won't until after the sapling update. Most people treat it as an investment more than a currency. Therefore, if dropping asic resistance is permitted, virtually the entire currency will fall into a natural oligopoly between however many asic makers enter the market. Maybe that will be okay after zcash is used as a currency more, but for now, it's privatizing the market.

**Comment by solarismedic** [comment]
@tony971 put yourself in their shoes. Why would you want to privatize and control the market that nobody uses or people have abandoned?  it's in everybody's best interest to see the value go up.  If I'm a gear manufacturer, I'd want to sell more gear and have a chance to develop the next generation gear year after year and sell more gear.  It's an ecosystem that is trying to be nurtured, i don't think any manufacturer wants to develop a bomb to blow up the coin they are trying to mine.  That's just not good business sense.

(btw, there is no coin that is being mined with GPUs that is seriously being used as a currency.  think about that for a moment.  if you're a payment processor, you'd be thinking about the same thing.  what is this coin backed with?  a bunch of hobbled together pc parts?  or does it have the backing of the semiconductor industry?  Also, trying to make sense of things when you're considering the 10s of thousands of dollars you have invested in GPU gear is hard.  Instead, think about what you'd do if this was day 1 and you are just starting to put skin in the game.  All I can say is, if ASICs are entering the market, hold onto everything you got.  the value is going to go up.  and that's no pump.)

**Comment by zookozcash** [comment]
Here's a question about the ballot: what sort of results will determine The Foundation's position? Is it simple majority? If 51% are in favor of ASIC-resistance and 49% are opposed, then the Foundation is in favor of ASIC-resistance?

**Comment by autotunafish** [comment]
I recently considered this and its potential consequences like being reduced to half a foundation, we must have faith that regardless of the outcome, their hearts are in the right place

**Comment by vannig** [comment]
@zookozcash 
 If 51% are in favor of ASIC-resistance and 49% are opposed, then the Foundation is in favor of ASIC-resistance?

Can't be anything better than this, I think. But here is too small activity and presence of possibly interested figures. It must be done as widespread as possible.

**Comment by vannig** [comment]
@solarismedic 
I don't want to argue with your statements. But there is a big reason that can cold my crypto enthusiasm  - Bitmain intervention. Nobody likes the smartest ones those who want to eat a cake for free and don't wish to wash dishes. Bitmain wants it all and besides, they make a big dump at your kitchen table and they want you to eat this with appetite and chant honorable odes to them.   
And also there are bruteforce and 3D Rendering purposes for our rigs.

**Comment by bjames301** [comment]
@zookozcash for me the ZCash team would need to prove to me that it would not end up in a massive consolidation of miners. Right now the only people who possibly could be cheering are those who have larger farms and can support lots of asics or those who are shills for BitMain.  Now if all a sudden I could buy asics from a US manufacture who didnt have warranties the likes of the Mobb I would be open to it. Many equihash coins have already announced a fork and its high time to let Bitmain know they dont run crypto, they are simply extensions of the technology.

**Comment by SzekelyVegan** [comment]
@bjames301 
Exactly. Most small miners (myself included) won't buy ASICs.
Bitmain is too greedy, we gotta slow them down a bit.

@zookozcash 
Simple majority sounds good.
If 50.01% votes anti-ASIC, change the algo and be done with it.
Show the community that you're really committed to spread the coins as far and wide as possible.

**Comment by ebfull** [comment]
I think instead we should be asking if we should upgrade to the `(144, 5)` Equihash parameters. It's more ASIC resistant, reduces block header size and verification costs, and it's what we would have preferred to launch with. I think it's also more likely to achieve widespread agreement in the community than this ballot, which vaguely proposes something much stronger: making ASIC resistance a value of the community and the Foundation.

ASIC resistance is just something you may do in pursuit of the value of _decentralization_. It might be the right thing now and not the right thing later, depending on what happens. I really worry this ballot will entrench us into an ASIC resistant attitude even when it flies in the face of technical reality later. There are lots of people who are financially motivated one way or another, so we should be wary of this outcome especially.

**Comment by solarismedic** [comment]
A voice of reason. I like it.

**Comment by bjames301** [comment]
@ebfull  I am very open to this approach if it gives us time for other ASIC manufactures to come up to speed and provide better customer and community service.

**Comment by mineZcash** [comment]
@ebfull I like the idea of tweaking the Equihash parameters asap to stave off the current batch of ASICs (if possible) and to buy us time to get a proper "other" possibly more exotic solution up and tested. But even if we can't do it before Sapling it at least gives us a place to start.

do we know the effects of RAM for `144, 5` ?

Another thing to consider is the fact that most, if not all GPU miners are running third party software (Claymore, Optiminer,etc) The only one I know of that is open source is NEHQ for Nvidia. Is there a way to test the new numbers? https://github.com/nicehash/nheqminer  I bet if we put it out to the mining community, they would start software testing.

**Comment by solarismedic** [comment]
You may want to work hand in hand with multiple manufacturers. This shows
good faith instead of heavy handledness and centralized decision making.
They are, frankly, part of the community also.

**Comment by ebfull** [comment]
By the way, I admit my proposal has several flaws:

1. We don't have any idea how much more ASIC resistant `144, 5` is, and how difficult it is for Bitmain to just adapt their hardware, so we might only be exposing ourselves to risk with little concrete gain.
2. If we make any change to disrupt ASICs, it's a lot less likely that in the future ASIC manufacturers will want to engage with Zcash again. So deciding now to stave off ASICs may stave them off for a long time.

See, this is hard! This is why we need a community-wide discussion about this stuff.

**Comment by flathashedtree** [comment]
I think advanced ASIC development can't be avoided.
Economics are a driving key force, and even if it does not apply right now, it applies next year.
Semiconductor manufacturing advancements  with cheaper die-bonding just makes it even easier.

However, let's say we introduce a PoW which is:
 1.  'easy' for a custom logic board with mainstream components.
 2. is hard to manufacture and economic nonsense to develop a custom integrated circuit for.
 3. and is also very hard to compute (or better simulate) on general purpose computing devices.

I am thinking of a configurable matrix of free-running oscillators.
Let's say we have a 'chaotic/random' system with very high entropy - which is converging until a certain state is archived,
every transition is plotted on a graph and at the end we derive a compressed proof for 'these are the paths I seen/tried out and here are all interesting intersections with a certain property you asked for'.

This PoW would be based on physical properties and is therefore be easy to verify,
but because of the sheer entropy, number of samples needed, high frequency probes - very hard to simulate.

And after a 3s search I found very nice work [1].
Can this be a serious solution for the future?

[1] http://www.slu.edu/~izkiss/PDF/Davidsen%202003%20Phys%20Rev%20E%20Rapid%20convergence%20of%20time-averaged%20frequency-1983956224/Davidsen%202003%20Phys%20Rev%20E%20Rapid%20convergence%20of%20time-averaged%20frequency.pdf

**Comment by spencerlambert** [comment]
In order to stay ASIC resistant, you'll need to change the PoW on a frequent scheduled basis, otherwise companies like Bitmain will simple secretly make ASIC hardware, leading to even more mining centralization than otherwise.

**Comment by Junior88** [comment]
It's faster, more efficient and cheaper. I think people forget the actual meaning of resistance, the inevitable will happen it is only a matter of when. I think more people should be concerned about becoming a competitor to Bitmain, which isn't to say their are other ASIC companies out there but Bitmain is the most well known. The GPU's that everyone is using for mining is hurting the gaming industry and causing over inflated GPU prices for old tech, more of a hassle to get setup and running and keep running. I like the old server speak of one server one role. This one device has a specific role and it does it extremely efficiently. Development time should be spent elsewhere. I am a GPU miner currently and have ordered 1 Z9.

**Comment by miningpersona** [comment]
I'm in favor of a PoW change, and yes possibly it should be dynamic so as to stay ahead of the ASIC manufacturers.  I've always found the ASIC manufactures to be scummy.  The whole preorder thing being so long you don't actually know if it will be profitable when it's delivered.  It makes a lot of sense that these ASIC man's make these things, they DO have to test them.  BUT if they test them long enough to mine 1 to 5X their cost before shipping?  They have the market cornered, by the time they deliver they have raised the hash rate and difficultly and collected up to 5X or more, now they deliver just in time to make the miner enough money to so he's ready buy the NEXT ASIC.
  I say make a PoW change that stops the ASIC (even temp) before they have delivered so they end up with a lot of PO'ed ASIC miners.  This will show some of the true colors of the ASIC Manufacturers.

**Comment by abc2006712** [comment]
Disagree.Support asic. Because this is a general trend, but it is necessary to control asic manufacturers.

**Pull request merged**
